config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :participants, only: [:new]
  resources :events do
    resources :participants, only: [:index, :create]
  end
end

app/models/admin.rb
class Admin < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'member' },
    { id: 3, name: 'admin' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ActiveHash::Base
  self.data = [
    { id: 1, name: '出席' },
    { id: 2, name: '欠席' },
    { id: 3, name: '未定' }
  ]
  include ActiveHash::Associations
  has_many :participants
end

app/models/count.rb
class Count < ApplicationRecord
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :participants
  has_many :users, through: :participants
  has_one :count

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :state

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :place, presence: true
  validates :fee, presence: true, numericality: { only_integer: true, in: 0..999_999 }
  validates :payer, presence: true
  validates :booker, presence: true
  validates :state_id, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :attendance
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
    { id: 1, name: 'open' },
    { id: 2, name: 'close' }
  ]
  include ActiveHash::Associations
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, through: :participants
  has_many :participants

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :admin

  validates :name, presence: true
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i,
                      message: 'is invalid. Input half-width alphanumeric characters.' }
  validates :admin_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.includes(:user).order('date ASC, start_time ASC, end_time ASC')

    @events.each do |event|
      count = event.count || event.build_count
      attendance = event.participants.where(attendance_id: 1).count
      absence = event.participants.where(attendance_id: 2).count
      undecided = event.participants.where(attendance_id: 3).count
      count.update(attendance:, absence:, undecided:)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(events_params)
    if @event.valid?
      @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @admin_int = 3
    @admin_str = '3'
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
    redirect_to root_path unless current_user_admin?
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(events_update_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    return unless current_user_admin? && user_signed_in?

    if @event.count.valid?
      @event.count.destroy
      if @event.participants.exists?
        @event.participants.destroy_all
        if @event.valid?
          @event.destroy
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
    redirect_to root_path
  end

  private

  def events_params
    params.require(:event).permit(:date, :start_time, :end_time, :place, :spot, :fee, :payer, :booker, :colum).merge(
      user_id: current_user.id, state_id: 1
    )
  end

  def events_update_params
    params.require(:event).permit(:date, :start_time, :end_time, :place, :spot, :fee, :payer, :booker, :colum,
                                  :state_id).merge(user_id: current_user.id)
  end

  def current_user_admin?
    current_user.admin_id == 3 || current_user.admin_id == '3'
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def new
    @events = Event.includes(:user).order('date ASC, start_time ASC, end_time ASC')
    @participant = Participant.new
    @participants = []
    @events.each do |event|
      @existing_participant = event.participants.find_by(user_id: current_user.id) || event.participants.create(
        user: current_user, attendance_id: 3
      )
      @participants << @existing_participant
    end
  end

  def create
    @event = Event.find(params[:event_id])
    @participant = @event.participants.find_by(user_id: current_user.id)
    if @participant.present?
      redirect_to new_participant_path, notice: 'RSVP successfully submitted.' if @participant.update(participant_update_params)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def participant_update_params
    params.require(:participant).permit(:attendance_id).merge(user_id: current_user.id, event_id: params[:event_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/events/show.html.erb
<!doctype html>
<html lang="jp" data-bs-theme="auto">
<head><!--<script src="../assets/js/color-modes.js"></script>-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.112.5">
  <title>Checkout example · Bootstrap v5.3</title>
  <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/checkout/">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }
    .bd-mode-toggle {
      z-index: 1500;
    }
  </style>

    
<!-- Custom styles for this template -->
</head>
<body class="bg-body-tertiary">
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
  </svg>

  <div class="container">
    <main>
      <div class="py-5 text-center">
        <%= link_to 'イベント詳細', root_path, class: 'h2 text-decoration-none' %>
      </div>
      <%= form_with model: @event, url: events_path, local: true do |f| %>
        <div class="row g-5">
          <div class="col">

            <div class="col">
              <label for="place" class="form-label">場所</label>
              <%= f.text_field :place, class:"form-control", id:"place", placeholder:"40文字まで", maxlength:"40" %>
              <div class="invalid-feedback">
                Valid place is required.
              </div>
            </div>

            <div class="col">
              <label for="spot" class="form-label">詳細</label>
              <%= f.text_field :spot, class:"form-control", id:"spot", placeholder:"" %>
            </div>

            <div class="col">
              <div class="d-flex align-items-center mt-4 mb-4">
                <label for="date" class="form-label">日付</label>
                <%= f.date_select( :date, 
                       use_month_numbers: true,  # 月に数字（1から12）を使用
                       prompt: { day: '日', month: '月', year: '年' },  # プロンプトの設定
                       order: [:year, :month, :day],  # セレクトボックスの順序
                       start_year: Time.now.year,  # 開始年
                       end_year: (Time.now.year + 5),  # 終了年
                  )%>
              </div>
              <div class="invalid-feedback">
                   Date is required.
              </div>
            </div>

            <div class="col mb-4">
              <label for="start_time" class="form-label">開始時間</label>
                <%= f.time_select(:start_time, 
                        class: 'time-select', 
                        twelve_hour: true,  # 12時間制表示を有効化
                        use_minute_seconds: false,  # 秒を使用しない
                        minute_step: 15  # 15分単位での選択を有効化
                )%>
              <div class="invalid-feedback">
                  Start time is required.
              </div>
              <label for="end_time" class="form-label"> ～ 終了時間</label>
                <%= f.time_select(:end_time, 
                        class: 'time-select', 
                        twelve_hour: true,  # 12時間制表示を有効化
                        use_minute_seconds: false,  # 秒を使用しない
                        minute_step: 15  # 15分単位での選択を有効化
                )%>
              <div class="invalid-feedback">
                  End time is required.
              </div>
            </div>

            <div class="col">
              <label for="fee" class="form-label">料金</label>
              
              <div class="input-group has-validation">
                <span class="input-group-text">¥</span>
                <%= f.text_field :fee, class:"form-control", id:"fee", placeholder:"" %>
              </div>
              <div class="invalid-feedback">
                   Fee is required.
              </div>
            </div>

            <div class="col">
              <label for="booker_name" class="form-label">予約者</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <%= f.text_field :booker, class:"form-control", id:"booker_name", placeholder:"" %>
              </div>
              <div class="invalid-feedback">
                   Booker name is required.
              </div>
            </div>

            <div class="col">
              <label for="payer_name" class="form-label">支払い者</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <%= f.text_field :payer, class:"form-control", id:"payer_name", placeholder:"" %>
              <div class="invalid-feedback">
                   Payer name is required.
              </div>
            </div>

            <div class="col">
              <label for="colum" class="form-label">備考欄</label>
              <%= f.text_area :colum, class:"form-control", id:"colum", placeholder:"" %>
            </div>

            <div class="col mt-4">
              <label for="state_id" class="form-label">ステータス</label>
              <%= f.collection_select(:state_id, State.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
            </div>

            <small class="text-body-secondary">
                    参加: <%= @event.count.attendance %>,
                    不参加: <%= @event.count.absence %>,
                    未定: <%= @event.count.undecided %>
            </small>
            <hr class="my-4">
            <div class="row justify-content-between">
              <% if current_user.admin_id == @admin_int || current_user.admin_id == @admin_str%>
                <div class="col"></div>
                <%= link_to '編集', edit_event_path(@event.id), class: 'w-25 btn btn-lg btn-primary' %>
                <div class="col"></div>
                <%= link_to '削除', event_path(@event.id), data: {turbo_method: :delete}, class: 'w-25 btn btn-lg btn-primary' %>
              <% end %>
              <div class="col"></div>
              <%= link_to 'back', root_path, class: 'w-25 btn btn-lg btn-secondary' %>
              <div class="col"></div>
            </div>
          </div>
        </div>
      <% end %>
    </main>
  </div>
  <footer class="my-5 pt-5 text-body-secondary text-center text-small">
    <p class="mb-1">&copy; 2017–2023 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventM2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>